workflows:
  android-release:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: 3.19.0
      java: 17

    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_app
          flutter pub get

      - name: Build APK
        script: |
          cd flutter_app
          flutter build apk --release --no-tree-shake-icons

    artifacts:
      - flutter_app/build/app/outputs/flutter-apk/app-release.apk
